<?php

/** @var Explanation $magewire */
use Xcom\MemoryGame\Magewire\MemoryGame;

/**
 * @var \Xcom\MemoryGame\Block\MemoryGame $block
 * @var \Xcom\MemoryGame\Magewire\MemoryGame $magewire
 */
?>
<div>
    <div class="grid grid-cols-4 gap-4">
        <?php
        $config = $magewire->getMemoryGameConfig();

        foreach ($config['cards'] as $card):
            ?>
            <div>
                <img src="<?= $card['url'] ?>" wire:click="foo" />
            </div>
        <?php endforeach; ?>
    </div>
</div>
